### ISSUE TITLE
Práctica 6

### ISSUE THREAD

**Issue by Rosa218** [SistemasTecTlaxiaco/practica-6-de-pruebas-unitarias-servitlax#1]
[Prueba unitaria.pdf](https://github.com/SistemasTecTlaxiaco/practica-6-de-pruebas-unitarias-servitlax/files/8912349/Prueba.unitaria.pdf)

**Comment by carlos-chrs** [comment]
calificado 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
